// =============================================
// Neo4j Cypher Script: SNP-Gene-Patient Database
// =============================================

// Step 1: Clear existing data (OPTIONAL - remove if you want to keep existing data)
// MATCH (n) DETACH DELETE n;

// Step 2: Create constraints for uniqueness
CREATE CONSTRAINT IF NOT EXISTS FOR (p:Patient) REQUIRE p.tcga_id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (g:Gene) REQUIRE g.hugo_symbol IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (s:SNP) REQUIRE s.dbsnp_rs IS UNIQUE;

// Step 3: Create Patient nodes
MERGE (p:Patient {tcga_id: "TCGA-AB-2802"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2807"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2808"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2816"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2821"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2822"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2826"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2830"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2838"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2839"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2843"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2847"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2860"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2861"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2863"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2864"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2865"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2867"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2869"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2870"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2871"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2874"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2881"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2884"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2887"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2892"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2901"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2914"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2917"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2919"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2920"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2923"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2926"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2928"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2929"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2930"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2932"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2937"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2939"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2943"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2945"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2949"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2952"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2959"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2966"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2967"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2968"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2969"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2972"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2977"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2978"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2982"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2983"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2984"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2985"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2987"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2990"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2992"});
MERGE (p:Patient {tcga_id: "TCGA-AB-2993"});
MERGE (p:Patient {tcga_id: "TCGA-AB-3008"});
MERGE (p:Patient {tcga_id: "TCGA-AB-3009"});
MERGE (p:Patient {tcga_id: "TCGA-AB-3011"});

// Step 4: Create Gene nodes
MERGE (g:Gene {hugo_symbol: "COL2A1"});
MERGE (g:Gene {hugo_symbol: "CRIPAK"});
MERGE (g:Gene {hugo_symbol: "DCLK1"});
MERGE (g:Gene {hugo_symbol: "DPYS"});
MERGE (g:Gene {hugo_symbol: "GNAI2"});
MERGE (g:Gene {hugo_symbol: "GPR123"});
MERGE (g:Gene {hugo_symbol: "IDH1"});
MERGE (g:Gene {hugo_symbol: "IL32"});
MERGE (g:Gene {hugo_symbol: "JAK2"});
MERGE (g:Gene {hugo_symbol: "KIT"});
MERGE (g:Gene {hugo_symbol: "KRAS"});
MERGE (g:Gene {hugo_symbol: "MED12"});
MERGE (g:Gene {hugo_symbol: "NF1"});
MERGE (g:Gene {hugo_symbol: "NFKBIZ"});
MERGE (g:Gene {hugo_symbol: "NRAS"});
MERGE (g:Gene {hugo_symbol: "PTPN11"});
MERGE (g:Gene {hugo_symbol: "RP3-393E18.1"});
MERGE (g:Gene {hugo_symbol: "RUNX1"});
MERGE (g:Gene {hugo_symbol: "THRB"});
MERGE (g:Gene {hugo_symbol: "TP53"});
MERGE (g:Gene {hugo_symbol: "WT1"});
MERGE (g:Gene {hugo_symbol: "ZNF175"});
MERGE (g:Gene {hugo_symbol: "ZNF681"});

// Step 5: Create SNP nodes
MERGE (s:SNP {dbsnp_rs: "rs104886029", variant_type: "SNP", hgvsp_short: "p.A59E"});
MERGE (s:SNP {dbsnp_rs: "rs112445441", variant_type: "SNP", hgvsp_short: "p.G13D"});
MERGE (s:SNP {dbsnp_rs: "rs113581628", variant_type: "INS"});
MERGE (s:SNP {dbsnp_rs: "rs11554290", variant_type: "SNP", hgvsp_short: "p.Q61P"});
MERGE (s:SNP {dbsnp_rs: "rs121434596", variant_type: "SNP", hgvsp_short: "p.G13D"});
MERGE (s:SNP {dbsnp_rs: "rs121907900", variant_type: "SNP", hgvsp_short: "p.R462W"});
MERGE (s:SNP {dbsnp_rs: "rs121912880", variant_type: "SNP", hgvsp_short: "p.G504C"});
MERGE (s:SNP {dbsnp_rs: "rs121913237", variant_type: "SNP", hgvsp_short: "p.G12D"});
MERGE (s:SNP {dbsnp_rs: "rs121913250", variant_type: "SNP", hgvsp_short: "p.G12C"});
MERGE (s:SNP {dbsnp_rs: "rs121913254", variant_type: "SNP", hgvsp_short: "p.Q61K"});
MERGE (s:SNP {dbsnp_rs: "rs121913255", variant_type: "SNP", hgvsp_short: "p.Q61H"});
MERGE (s:SNP {dbsnp_rs: "rs121913343", variant_type: "SNP", hgvsp_short: "p.R273C"});
MERGE (s:SNP {dbsnp_rs: "rs121913499", variant_type: "SNP", hgvsp_short: "p.R132C"});
MERGE (s:SNP {dbsnp_rs: "rs121913500", variant_type: "SNP", hgvsp_short: "p.R132H"});
MERGE (s:SNP {dbsnp_rs: "rs121913506", variant_type: "SNP", hgvsp_short: "p.D816Y"});
MERGE (s:SNP {dbsnp_rs: "rs121913507", variant_type: "SNP", hgvsp_short: "p.D816V"});
MERGE (s:SNP {dbsnp_rs: "rs121913527", variant_type: "SNP", hgvsp_short: "p.A146T"});
MERGE (s:SNP {dbsnp_rs: "rs121913529", variant_type: "SNP", hgvsp_short: "p.G12D"});
MERGE (s:SNP {dbsnp_rs: "rs121918454", variant_type: "SNP", hgvsp_short: "p.A72V"});
MERGE (s:SNP {dbsnp_rs: "rs121918458", variant_type: "SNP", hgvsp_short: "p.S502P"});
MERGE (s:SNP {dbsnp_rs: "rs121918470", variant_type: "SNP", hgvsp_short: "p.Q510L"});
MERGE (s:SNP {dbsnp_rs: "rs121918697", variant_type: "SNP", hgvsp_short: "p.R338W"});
MERGE (s:SNP {dbsnp_rs: "rs137853227", variant_type: "SNP", hgvsp_short: "p.R179H"});
MERGE (s:SNP {dbsnp_rs: "rs137854556", variant_type: "SNP", hgvsp_short: "p.R1276Q"});
MERGE (s:SNP {dbsnp_rs: "rs17851045", variant_type: "SNP", hgvsp_short: "p.Q61H"});
MERGE (s:SNP {dbsnp_rs: "rs181856403", variant_type: "SNP", hgvsp_short: "p.T38I"});
MERGE (s:SNP {dbsnp_rs: "rs33981747", variant_type: "INS", hgvsp_short: "p.X645_splice"});
MERGE (s:SNP {dbsnp_rs: "rs34051457", variant_type: "DEL", hgvsp_short: "p.T17Vfs*390"});
MERGE (s:SNP {dbsnp_rs: "rs55863639", variant_type: "SNP", hgvsp_short: "p.T125="});
MERGE (s:SNP {dbsnp_rs: "rs56185003", variant_type: "SNP", hgvsp_short: "p.R292H"});
MERGE (s:SNP {dbsnp_rs: "rs61112029", variant_type: "INS", hgvsp_short: "*61*"});
MERGE (s:SNP {dbsnp_rs: "rs61397759", variant_type: "DEL", hgvsp_short: "p.C203Wfs*5"});
MERGE (s:SNP {dbsnp_rs: "rs71818662", variant_type: "INS", hgvsp_short: "p.D172Gfs*12"});
MERGE (s:SNP {dbsnp_rs: "rs71889021", variant_type: "DEL", hgvsp_short: "*482*"});
MERGE (s:SNP {dbsnp_rs: "rs74315450", variant_type: "SNP", hgvsp_short: "p.R201Q"});
MERGE (s:SNP {dbsnp_rs: "rs77375493", variant_type: "SNP", hgvsp_short: "p.V617F"});
MERGE (s:SNP {dbsnp_rs: "rs80338758", variant_type: "SNP", hgvsp_short: "p.R961W"});

// Step 6: Create relationships
// SNP -[:LOCATED_IN]-> Gene
// SNP -[:FOUND_IN_PATIENT]-> Patient
// SNP -[:HAS_CONSEQUENCE]-> (consequence as relationship property)

MATCH (s:SNP {dbsnp_rs: "rs104886029"}), (g:Gene {hugo_symbol: "KRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs112445441"}), (g:Gene {hugo_symbol: "KRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs113581628"}), (g:Gene {hugo_symbol: "ZNF175"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs11554290"}), (g:Gene {hugo_symbol: "NRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121434596"}), (g:Gene {hugo_symbol: "NRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121907900"}), (g:Gene {hugo_symbol: "WT1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121912880"}), (g:Gene {hugo_symbol: "COL2A1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913237"}), (g:Gene {hugo_symbol: "NRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913250"}), (g:Gene {hugo_symbol: "NRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913254"}), (g:Gene {hugo_symbol: "NRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913255"}), (g:Gene {hugo_symbol: "NRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913343"}), (g:Gene {hugo_symbol: "TP53"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (g:Gene {hugo_symbol: "IDH1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913500"}), (g:Gene {hugo_symbol: "IDH1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913506"}), (g:Gene {hugo_symbol: "KIT"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913507"}), (g:Gene {hugo_symbol: "KIT"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913527"}), (g:Gene {hugo_symbol: "KRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121913529"}), (g:Gene {hugo_symbol: "KRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121918454"}), (g:Gene {hugo_symbol: "PTPN11"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121918458"}), (g:Gene {hugo_symbol: "PTPN11"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121918470"}), (g:Gene {hugo_symbol: "PTPN11"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs121918697"}), (g:Gene {hugo_symbol: "THRB"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs137853227"}), (g:Gene {hugo_symbol: "GNAI2"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs137854556"}), (g:Gene {hugo_symbol: "NF1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs17851045"}), (g:Gene {hugo_symbol: "KRAS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs181856403"}), (g:Gene {hugo_symbol: "GPR123"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs33981747"}), (g:Gene {hugo_symbol: "NFKBIZ"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs34051457"}), (g:Gene {hugo_symbol: "CRIPAK"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs55863639"}), (g:Gene {hugo_symbol: "TP53"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs56185003"}), (g:Gene {hugo_symbol: "DCLK1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs61112029"}), (g:Gene {hugo_symbol: "RP3-393E18.1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs61397759"}), (g:Gene {hugo_symbol: "ZNF681"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs71818662"}), (g:Gene {hugo_symbol: "IL32"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs71889021"}), (g:Gene {hugo_symbol: "DPYS"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs74315450"}), (g:Gene {hugo_symbol: "RUNX1"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs77375493"}), (g:Gene {hugo_symbol: "JAK2"}) MERGE (s)-[:LOCATED_IN]->(g);
MATCH (s:SNP {dbsnp_rs: "rs80338758"}), (g:Gene {hugo_symbol: "MED12"}) MERGE (s)-[:LOCATED_IN]->(g);

MATCH (s:SNP {dbsnp_rs: "rs104886029"}), (p:Patient {tcga_id: "TCGA-AB-2864"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs112445441"}), (p:Patient {tcga_id: "TCGA-AB-2987"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs113581628"}), (p:Patient {tcga_id: "TCGA-AB-2939"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "downstream_gene_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs113581628"}), (p:Patient {tcga_id: "TCGA-AB-3008"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "downstream_gene_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs11554290"}), (p:Patient {tcga_id: "TCGA-AB-2923"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs11554290"}), (p:Patient {tcga_id: "TCGA-AB-2978"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121434596"}), (p:Patient {tcga_id: "TCGA-AB-2808"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121434596"}), (p:Patient {tcga_id: "TCGA-AB-2816"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121434596"}), (p:Patient {tcga_id: "TCGA-AB-2839"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121434596"}), (p:Patient {tcga_id: "TCGA-AB-2932"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121434596"}), (p:Patient {tcga_id: "TCGA-AB-2967"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121907900"}), (p:Patient {tcga_id: "TCGA-AB-2874"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121912880"}), (p:Patient {tcga_id: "TCGA-AB-2983"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913237"}), (p:Patient {tcga_id: "TCGA-AB-2887"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913237"}), (p:Patient {tcga_id: "TCGA-AB-2952"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913237"}), (p:Patient {tcga_id: "TCGA-AB-2984"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913250"}), (p:Patient {tcga_id: "TCGA-AB-2985"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913254"}), (p:Patient {tcga_id: "TCGA-AB-2870"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913254"}), (p:Patient {tcga_id: "TCGA-AB-2892"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913255"}), (p:Patient {tcga_id: "TCGA-AB-2838"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913255"}), (p:Patient {tcga_id: "TCGA-AB-2968"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913343"}), (p:Patient {tcga_id: "TCGA-AB-2943"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2821"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2822"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2863"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2867"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2887"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2901"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2919"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2926"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2928"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2977"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2984"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2990"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-2992"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913499"}), (p:Patient {tcga_id: "TCGA-AB-3011"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913500"}), (p:Patient {tcga_id: "TCGA-AB-2802"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913500"}), (p:Patient {tcga_id: "TCGA-AB-2884"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913500"}), (p:Patient {tcga_id: "TCGA-AB-2945"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913500"}), (p:Patient {tcga_id: "TCGA-AB-2949"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913500"}), (p:Patient {tcga_id: "TCGA-AB-2969"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913506"}), (p:Patient {tcga_id: "TCGA-AB-2881"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913507"}), (p:Patient {tcga_id: "TCGA-AB-2843"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913507"}), (p:Patient {tcga_id: "TCGA-AB-2937"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913507"}), (p:Patient {tcga_id: "TCGA-AB-2939"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913507"}), (p:Patient {tcga_id: "TCGA-AB-2945"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913527"}), (p:Patient {tcga_id: "TCGA-AB-2966"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913529"}), (p:Patient {tcga_id: "TCGA-AB-2861"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913529"}), (p:Patient {tcga_id: "TCGA-AB-2865"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121913529"}), (p:Patient {tcga_id: "TCGA-AB-2929"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121918454"}), (p:Patient {tcga_id: "TCGA-AB-2914"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121918458"}), (p:Patient {tcga_id: "TCGA-AB-2972"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121918470"}), (p:Patient {tcga_id: "TCGA-AB-2871"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs121918697"}), (p:Patient {tcga_id: "TCGA-AB-2830"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs137853227"}), (p:Patient {tcga_id: "TCGA-AB-3009"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs137854556"}), (p:Patient {tcga_id: "TCGA-AB-2920"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs17851045"}), (p:Patient {tcga_id: "TCGA-AB-2826"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs181856403"}), (p:Patient {tcga_id: "TCGA-AB-2993"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs33981747"}), (p:Patient {tcga_id: "TCGA-AB-2869"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "splice_region_variant,intron_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs34051457"}), (p:Patient {tcga_id: "TCGA-AB-2847"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "frameshift_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs55863639"}), (p:Patient {tcga_id: "TCGA-AB-2838"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "splice_region_variant,synonymous_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs56185003"}), (p:Patient {tcga_id: "TCGA-AB-2807"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs61112029"}), (p:Patient {tcga_id: "TCGA-AB-2930"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "non_coding_transcript_exon_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs61397759"}), (p:Patient {tcga_id: "TCGA-AB-2860"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "frameshift_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs71818662"}), (p:Patient {tcga_id: "TCGA-AB-2939"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "frameshift_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs71889021"}), (p:Patient {tcga_id: "TCGA-AB-2982"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "intron_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs74315450"}), (p:Patient {tcga_id: "TCGA-AB-2959"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs77375493"}), (p:Patient {tcga_id: "TCGA-AB-2865"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);
MATCH (s:SNP {dbsnp_rs: "rs80338758"}), (p:Patient {tcga_id: "TCGA-AB-2917"}) MERGE (s)-[:FOUND_IN_PATIENT {consequence: "missense_variant"}]->(p);